"""add target_categories table

Revision ID: 0e1413193bcd
Revises: 77261915680b
Create Date: 2026-02-05 23:21:11.527769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e1413193bcd'
down_revision: Union[str, Sequence[str], None] = '77261915680b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('target_categories', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('target_categories', 'youtube_query',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('target_categories', 'parent_category',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_target_categories_id'), 'target_categories', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_target_categories_id'), table_name='target_categories')
    op.alter_column('target_categories', 'parent_category',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('target_categories', 'youtube_query',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('target_categories', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
