"""Added ai prompt instructions col

Revision ID: 285f6aea6d55
Revises: b54e4edda368
Create Date: 2026-02-11 09:27:36.381095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '285f6aea6d55'
down_revision: Union[str, Sequence[str], None] = 'b54e4edda368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('campaigns_template_id_fkey'), 'campaigns', type_='foreignkey')
    op.create_foreign_key(None, 'campaigns', 'email_templates', ['template_id'], ['id'])
    op.add_column('email_templates', sa.Column('ai_prompt_instructions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_templates', 'ai_prompt_instructions')
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.create_foreign_key(op.f('campaigns_template_id_fkey'), 'campaigns', 'outreach_templates', ['template_id'], ['id'])
    # ### end Alembic commands ###
