"""Added video id in lead

Revision ID: 53f6d15aab8b
Revises: 69380c3eed82
Create Date: 2026-02-12 23:55:48.964446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53f6d15aab8b'
down_revision: Union[str, Sequence[str], None] = '69380c3eed82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('video_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'leads', ['video_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leads', type_='unique')
    op.drop_column('leads', 'video_id')
    # ### end Alembic commands ###
