"""Added ai prompt instructions col

Revision ID: 69380c3eed82
Revises: 285f6aea6d55
Create Date: 2026-02-11 10:20:13.615377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69380c3eed82'
down_revision: Union[str, Sequence[str], None] = '285f6aea6d55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outreach_templates_id'), table_name='outreach_templates')
    op.drop_table('outreach_templates')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outreach_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_ai_powered', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('subject_template', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('body_template', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('usage_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avg_response_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('outreach_templates_pkey'))
    )
    op.create_index(op.f('ix_outreach_templates_id'), 'outreach_templates', ['id'], unique=False)
    # ### end Alembic commands ###
