"""initial schema

Revision ID: 77261915680b
Revises: 
Create Date: 2026-02-05 16:41:23.758011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77261915680b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_usage_logs', 'task_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('ai_usage_logs', 'model_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('ai_usage_logs', 'related_channel_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('ai_usage_logs', 'related_video_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('ai_usage_logs', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'success'::text"))
    op.create_index(op.f('ix_ai_usage_logs_id'), 'ai_usage_logs', ['id'], unique=False)
    op.alter_column('automation_jobs', 'job_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('automation_jobs', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'queued'::text"))
    op.drop_index(op.f('idx_jobs_status'), table_name='automation_jobs')
    op.drop_index(op.f('idx_jobs_type'), table_name='automation_jobs')
    op.create_index(op.f('ix_automation_jobs_id'), 'automation_jobs', ['id'], unique=False)
    op.alter_column('category_stats', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_category_date'), table_name='category_stats')
    op.alter_column('channel_metrics', 'channel_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('channel_metrics_channel_id_fkey'), 'channel_metrics', type_='foreignkey')
    op.alter_column('channel_social_links', 'channel_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('channel_social_links', 'platform',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('channel_social_links', 'url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('idx_social_channel'), table_name='channel_social_links')
    op.drop_index(op.f('idx_social_platform'), table_name='channel_social_links')
    op.create_index(op.f('ix_channel_social_links_id'), 'channel_social_links', ['id'], unique=False)
    op.drop_constraint(op.f('channel_social_links_channel_id_fkey'), 'channel_social_links', type_='foreignkey')
    op.alter_column('country_stats', 'country_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_country_date'), table_name='country_stats')
    op.alter_column('email_messages', 'lead_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('email_messages', 'email',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('email_messages', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('email_messages', 'provider',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_emailmsg_lead'), table_name='email_messages')
    op.drop_index(op.f('idx_emailmsg_sent'), table_name='email_messages')
    op.drop_index(op.f('idx_emailmsg_status'), table_name='email_messages')
    op.create_index(op.f('ix_email_messages_id'), 'email_messages', ['id'], unique=False)
    op.drop_constraint(op.f('email_messages_lead_id_fkey'), 'email_messages', type_='foreignkey')
    op.alter_column('email_templates', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('email_templates', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_email_templates_id'), 'email_templates', ['id'], unique=False)
    op.drop_constraint(op.f('email_templates_user_id_fkey'), 'email_templates', type_='foreignkey')
    op.alter_column('error_logs', 'service',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('error_logs', 'error_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('error_logs', 'related_channel_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_error_created'), table_name='error_logs')
    op.drop_index(op.f('idx_error_resolved'), table_name='error_logs')
    op.drop_index(op.f('idx_error_service'), table_name='error_logs')
    op.create_index(op.f('ix_error_logs_id'), 'error_logs', ['id'], unique=False)
    op.alter_column('extracted_emails', 'channel_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('extracted_emails', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'new'::text"))
    op.drop_index(op.f('idx_emails_channel'), table_name='extracted_emails')
    op.drop_index(op.f('idx_emails_email'), table_name='extracted_emails')
    op.drop_index(op.f('idx_emails_status'), table_name='extracted_emails')
    op.create_index(op.f('ix_extracted_emails_id'), 'extracted_emails', ['id'], unique=False)
    op.drop_constraint(op.f('extracted_emails_channel_id_fkey'), 'extracted_emails', type_='foreignkey')
    op.alter_column('instagram_actions', 'channel_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('instagram_actions', 'action_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('instagram_actions', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_ig_channel'), table_name='instagram_actions')
    op.drop_index(op.f('idx_ig_executed'), table_name='instagram_actions')
    op.drop_index(op.f('idx_ig_status'), table_name='instagram_actions')
    op.create_index(op.f('ix_instagram_actions_id'), 'instagram_actions', ['id'], unique=False)
    op.drop_constraint(op.f('instagram_actions_channel_id_fkey'), 'instagram_actions', type_='foreignkey')
    op.alter_column('leads', 'channel_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('leads', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'new'::text"))
    op.drop_index(op.f('idx_leads_channel'), table_name='leads')
    op.drop_index(op.f('idx_leads_status'), table_name='leads')
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.drop_constraint(op.f('leads_channel_id_fkey'), 'leads', type_='foreignkey')
    op.alter_column('saved_filters', 'filter_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_saved_filters_id'), 'saved_filters', ['id'], unique=False)
    op.drop_constraint(op.f('saved_filters_user_id_fkey'), 'saved_filters', type_='foreignkey')
    op.alter_column('saved_views', 'layout_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_saved_views_id'), 'saved_views', ['id'], unique=False)
    op.drop_constraint(op.f('saved_views_user_id_fkey'), 'saved_views', type_='foreignkey')
    op.alter_column('system_logs', 'service',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('system_logs', 'level',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('system_logs', 'related_channel_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_syslog_created'), table_name='system_logs')
    op.drop_index(op.f('idx_syslog_level'), table_name='system_logs')
    op.drop_index(op.f('idx_syslog_service'), table_name='system_logs')
    op.create_index(op.f('ix_system_logs_id'), 'system_logs', ['id'], unique=False)
    op.alter_column('template_usage', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_template_usage_id'), 'template_usage', ['id'], unique=False)
    op.drop_constraint(op.f('template_usage_template_id_fkey'), 'template_usage', type_='foreignkey')
    op.drop_constraint(op.f('template_usage_lead_id_fkey'), 'template_usage', type_='foreignkey')
    op.alter_column('user_settings', 'timezone',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'UTC'::text"))
    op.alter_column('user_settings', 'preferred_ai_model',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'gemini'::text"))
    op.alter_column('user_settings', 'email_provider',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'zoho'::text"))
    op.drop_constraint(op.f('user_settings_user_id_fkey'), 'user_settings', type_='foreignkey')
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('users', 'full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'user'::text"))
    op.alter_column('users', 'plan',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'free'::text"))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('youtube_channels', 'channel_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_channels_country'), table_name='youtube_channels')
    op.drop_index(op.f('idx_channels_discovered'), table_name='youtube_channels')
    op.drop_index(op.f('idx_channels_email'), table_name='youtube_channels')
    op.drop_index(op.f('idx_channels_instagram'), table_name='youtube_channels')
    op.create_index(op.f('ix_youtube_channels_channel_id'), 'youtube_channels', ['channel_id'], unique=False)
    op.alter_column('youtube_videos', 'video_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('youtube_videos', 'channel_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.drop_index(op.f('idx_videos_channel'), table_name='youtube_videos')
    op.drop_index(op.f('idx_videos_published'), table_name='youtube_videos')
    op.create_index(op.f('ix_youtube_videos_video_id'), 'youtube_videos', ['video_id'], unique=False)
    op.drop_constraint(op.f('youtube_videos_channel_id_fkey'), 'youtube_videos', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('youtube_videos_channel_id_fkey'), 'youtube_videos', 'youtube_channels', ['channel_id'], ['channel_id'])
    op.drop_index(op.f('ix_youtube_videos_video_id'), table_name='youtube_videos')
    op.create_index(op.f('idx_videos_published'), 'youtube_videos', ['published_at'], unique=False)
    op.create_index(op.f('idx_videos_channel'), 'youtube_videos', ['channel_id'], unique=False)
    op.alter_column('youtube_videos', 'channel_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('youtube_videos', 'video_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_youtube_channels_channel_id'), table_name='youtube_channels')
    op.create_index(op.f('idx_channels_instagram'), 'youtube_channels', ['has_instagram'], unique=False)
    op.create_index(op.f('idx_channels_email'), 'youtube_channels', ['has_email'], unique=False)
    op.create_index(op.f('idx_channels_discovered'), 'youtube_channels', ['discovered_at'], unique=False)
    op.create_index(op.f('idx_channels_country'), 'youtube_channels', ['country_code'], unique=False)
    op.alter_column('youtube_channels', 'channel_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'plan',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'free'::text"))
    op.alter_column('users', 'role',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'user'::text"))
    op.alter_column('users', 'full_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.create_foreign_key(op.f('user_settings_user_id_fkey'), 'user_settings', 'users', ['user_id'], ['id'])
    op.alter_column('user_settings', 'email_provider',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'zoho'::text"))
    op.alter_column('user_settings', 'preferred_ai_model',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'gemini'::text"))
    op.alter_column('user_settings', 'timezone',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'UTC'::text"))
    op.create_foreign_key(op.f('template_usage_lead_id_fkey'), 'template_usage', 'leads', ['lead_id'], ['id'])
    op.create_foreign_key(op.f('template_usage_template_id_fkey'), 'template_usage', 'email_templates', ['template_id'], ['id'])
    op.drop_index(op.f('ix_template_usage_id'), table_name='template_usage')
    op.alter_column('template_usage', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_system_logs_id'), table_name='system_logs')
    op.create_index(op.f('idx_syslog_service'), 'system_logs', ['service'], unique=False)
    op.create_index(op.f('idx_syslog_level'), 'system_logs', ['level'], unique=False)
    op.create_index(op.f('idx_syslog_created'), 'system_logs', ['created_at'], unique=False)
    op.alter_column('system_logs', 'related_channel_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('system_logs', 'level',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('system_logs', 'service',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_foreign_key(op.f('saved_views_user_id_fkey'), 'saved_views', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_saved_views_id'), table_name='saved_views')
    op.alter_column('saved_views', 'layout_json',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_foreign_key(op.f('saved_filters_user_id_fkey'), 'saved_filters', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_saved_filters_id'), table_name='saved_filters')
    op.alter_column('saved_filters', 'filter_json',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_foreign_key(op.f('leads_channel_id_fkey'), 'leads', 'youtube_channels', ['channel_id'], ['channel_id'])
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.create_index(op.f('idx_leads_status'), 'leads', ['status'], unique=False)
    op.create_index(op.f('idx_leads_channel'), 'leads', ['channel_id'], unique=False)
    op.alter_column('leads', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'new'::text"))
    op.alter_column('leads', 'channel_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.create_foreign_key(op.f('instagram_actions_channel_id_fkey'), 'instagram_actions', 'youtube_channels', ['channel_id'], ['channel_id'])
    op.drop_index(op.f('ix_instagram_actions_id'), table_name='instagram_actions')
    op.create_index(op.f('idx_ig_status'), 'instagram_actions', ['status'], unique=False)
    op.create_index(op.f('idx_ig_executed'), 'instagram_actions', ['executed_at'], unique=False)
    op.create_index(op.f('idx_ig_channel'), 'instagram_actions', ['channel_id'], unique=False)
    op.alter_column('instagram_actions', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('instagram_actions', 'action_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('instagram_actions', 'channel_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_foreign_key(op.f('extracted_emails_channel_id_fkey'), 'extracted_emails', 'youtube_channels', ['channel_id'], ['channel_id'])
    op.drop_index(op.f('ix_extracted_emails_id'), table_name='extracted_emails')
    op.create_index(op.f('idx_emails_status'), 'extracted_emails', ['status'], unique=False)
    op.create_index(op.f('idx_emails_email'), 'extracted_emails', ['email'], unique=False)
    op.create_index(op.f('idx_emails_channel'), 'extracted_emails', ['channel_id'], unique=False)
    op.alter_column('extracted_emails', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'new'::text"))
    op.alter_column('extracted_emails', 'channel_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.drop_index(op.f('ix_error_logs_id'), table_name='error_logs')
    op.create_index(op.f('idx_error_service'), 'error_logs', ['service'], unique=False)
    op.create_index(op.f('idx_error_resolved'), 'error_logs', ['resolved'], unique=False)
    op.create_index(op.f('idx_error_created'), 'error_logs', ['created_at'], unique=False)
    op.alter_column('error_logs', 'related_channel_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('error_logs', 'error_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('error_logs', 'service',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_foreign_key(op.f('email_templates_user_id_fkey'), 'email_templates', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_email_templates_id'), table_name='email_templates')
    op.alter_column('email_templates', 'category',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('email_templates', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_foreign_key(op.f('email_messages_lead_id_fkey'), 'email_messages', 'leads', ['lead_id'], ['id'])
    op.drop_index(op.f('ix_email_messages_id'), table_name='email_messages')
    op.create_index(op.f('idx_emailmsg_status'), 'email_messages', ['status'], unique=False)
    op.create_index(op.f('idx_emailmsg_sent'), 'email_messages', ['sent_at'], unique=False)
    op.create_index(op.f('idx_emailmsg_lead'), 'email_messages', ['lead_id'], unique=False)
    op.alter_column('email_messages', 'provider',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('email_messages', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('email_messages', 'email',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('email_messages', 'lead_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('idx_country_date'), 'country_stats', ['country_code', 'stat_date'], unique=False)
    op.alter_column('country_stats', 'country_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_foreign_key(op.f('channel_social_links_channel_id_fkey'), 'channel_social_links', 'youtube_channels', ['channel_id'], ['channel_id'])
    op.drop_index(op.f('ix_channel_social_links_id'), table_name='channel_social_links')
    op.create_index(op.f('idx_social_platform'), 'channel_social_links', ['platform'], unique=False)
    op.create_index(op.f('idx_social_channel'), 'channel_social_links', ['channel_id'], unique=False)
    op.alter_column('channel_social_links', 'url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('channel_social_links', 'platform',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('channel_social_links', 'channel_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.create_foreign_key(op.f('channel_metrics_channel_id_fkey'), 'channel_metrics', 'youtube_channels', ['channel_id'], ['channel_id'])
    op.alter_column('channel_metrics', 'channel_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('idx_category_date'), 'category_stats', ['category', 'stat_date'], unique=False)
    op.alter_column('category_stats', 'category',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_automation_jobs_id'), table_name='automation_jobs')
    op.create_index(op.f('idx_jobs_type'), 'automation_jobs', ['job_type'], unique=False)
    op.create_index(op.f('idx_jobs_status'), 'automation_jobs', ['status'], unique=False)
    op.alter_column('automation_jobs', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'queued'::text"))
    op.alter_column('automation_jobs', 'job_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.drop_index(op.f('ix_ai_usage_logs_id'), table_name='ai_usage_logs')
    op.alter_column('ai_usage_logs', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'success'::text"))
    op.alter_column('ai_usage_logs', 'related_video_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ai_usage_logs', 'related_channel_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ai_usage_logs', 'model_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ai_usage_logs', 'task_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
