"""add_category_to_channel

Revision ID: b54e4edda368
Revises: f97e8d0a61c8
Create Date: 2026-02-10 15:47:27.058893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b54e4edda368'
down_revision: Union[str, Sequence[str], None] = 'f97e8d0a61c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('youtube_channels', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'youtube_channels', 'target_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'youtube_channels', type_='foreignkey')
    op.drop_column('youtube_channels', 'category_id')
    # ### end Alembic commands ###
