"""add_campaign_tables

Revision ID: f97e8d0a61c8
Revises: 3feae6fcecdb
Create Date: 2026-02-09 09:09:15.121401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f97e8d0a61c8'
down_revision: Union[str, Sequence[str], None] = '3feae6fcecdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outreach_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('is_ai_powered', sa.Boolean(), nullable=True),
    sa.Column('subject_template', sa.Text(), nullable=True),
    sa.Column('body_template', sa.Text(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('avg_response_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_templates_id'), 'outreach_templates', ['id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_start', sa.TIMESTAMP(), nullable=True),
    sa.Column('daily_limit', sa.Integer(), nullable=True),
    sa.Column('total_leads', sa.Integer(), nullable=True),
    sa.Column('generated_count', sa.Integer(), nullable=True),
    sa.Column('sent_count', sa.Integer(), nullable=True),
    sa.Column('opened_count', sa.Integer(), nullable=True),
    sa.Column('replied_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['outreach_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.create_table('campaign_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('ai_generated_subject', sa.Text(), nullable=True),
    sa.Column('ai_generated_body', sa.Text(), nullable=True),
    sa.Column('context_snapshot', sa.JSON(), nullable=True),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('sent_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('opened_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('replied_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_leads_id'), 'campaign_leads', ['id'], unique=False)
    op.create_table('campaign_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_lead_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_lead_id'], ['campaign_leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_events_id'), 'campaign_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaign_events_id'), table_name='campaign_events')
    op.drop_table('campaign_events')
    op.drop_index(op.f('ix_campaign_leads_id'), table_name='campaign_leads')
    op.drop_table('campaign_leads')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_outreach_templates_id'), table_name='outreach_templates')
    op.drop_table('outreach_templates')
    # ### end Alembic commands ###
